_BASE_: "../Base-RCNN-FPN-CTF.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # WEIGHTS: "./output/model_final.pth"
  WEIGHTS: "./output/model_0059999.pth"

  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
